export const ADD_ARTICLE = "ADD_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE"
export const INPUT_ONCHANGE = 'INPUT_ONCHANGE'
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE'
export const EDIT_ARTICLE = 'EDIT_ARTICLE'